name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Este workflow se ejecutará cada vez que se haga un push en la rama main

jobs:
  # Job para ejecutar los tests
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Usa la versión de Node.js que tengas en tu Dockerfile

      - name: Install dependencies
        run: npm install  # Cambié esto a npm, ya que en el Dockerfile usas npm

      - name: Run tests
        run: npm test  # Ejecuta los tests definidos en tu proyecto

  # Job para construir y subir la imagen Docker
  build_and_push:
    runs-on: ubuntu-latest
    needs: test  # Este job solo se ejecutará si los tests fueron exitosos

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
